// src/app/og/generatePuzzleOgMeta.ts
//
// Generates functions/puzzleOgMeta.generated.ts (gitignored) — per-puzzle
// OG title/description for the T11 unfurl (functions/puzzle/[id].ts).
//
// Same reasoning as workers/scripts/generatePuzzleIds.mjs: the real puzzle-
// metadata index (src/content/index.ts's `puzzleMeta`) is populated via
// `import { PUZZLE_META } from 'virtual:codoro-puzzle-meta'`, a Vite virtual
// module resolved only inside the root Vite build. Cloudflare Pages
// Functions are bundled by wrangler's own esbuild, which has no knowledge
// of Vite plugins and cannot resolve that specifier. This script is an
// independent reader of the same source files (src/content/puzzles/**/*.json),
// not a hand-maintained duplicate — same "one source of truth, two readers"
// posture as puzzleIds.generated.ts.
//
// Unlike puzzleIds.generated.ts, this script runs under tsx (a Node
// runtime), not wrangler's bundler, so it's safe for it to import PATTERN_LABELS
// directly from src/content/patterns.ts — that module has no dependency on
// the Vite virtual module, so this is reuse, not duplication.
//
// Run before typecheck/lint/test/build (see package.json) so the generated
// file is never stale relative to content.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { PATTERN_LABELS } from '../../content/patterns'
import type { PatternSlug } from '../../content/patterns'

const here = dirname(fileURLToPath(import.meta.url))
const puzzlesDir = join(here, '../../content/puzzles')
const outFile = join(here, '../../../functions/puzzleOgMeta.generated.ts')

interface RawPuzzleJson {
  id: unknown
  pattern: unknown
  prompt: unknown
}

function walk(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const fullPath = join(dir, entry.name)
    if (entry.isDirectory()) return walk(fullPath)
    return entry.name.endsWith('.json') ? [fullPath] : []
  })
}

/** Meta-description best practice caps around 155-160 chars — truncate defensively, same "cap even though the schema should already bound it" posture as challenge.ts's sanitizeOgName. */
function truncate(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text
  return `${text.slice(0, maxLength - 1).trimEnd()}…`
}

const entries: [string, { title: string; description: string }][] = walk(puzzlesDir)
  .sort()
  .map((filePath) => {
    const raw = JSON.parse(readFileSync(filePath, 'utf-8')) as RawPuzzleJson
    const id = String(raw.id)
    const pattern = raw.pattern as PatternSlug
    const prompt = String(raw.prompt)
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
    const label = PATTERN_LABELS[pattern] ?? 'Coding'
    return [
      id,
      {
        title: `${label} puzzle — Codoro`,
        description: truncate(prompt, 155),
      },
    ]
  })

const contents = `// GENERATED by src/app/og/generatePuzzleOgMeta.ts -- do not edit by hand,
// and do not commit (gitignored). Regenerated automatically before
// typecheck/lint/test/build (package.json). Source of truth:
// src/content/puzzles/**/*.json -- see this script's own comment for why
// functions/ reads them independently instead of importing the SPA's
// Vite-only puzzleMeta module.
export const PUZZLE_OG_META: ReadonlyMap<string, { title: string; description: string }> = new Map(${JSON.stringify(entries)})
`

writeFileSync(outFile, contents)
console.log(`generatePuzzleOgMeta: wrote ${String(entries.length)} entries to ${outFile}`)
