/// <reference types="node" />
import { describe, it, expect } from 'vitest'
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import process from 'node:process'
import prettier from 'prettier'
import { INITIAL_RATING, roundForDisplay } from './rating'
import { createRng, simulate } from './convergence'
import type { SimulationResult } from './convergence'

const PUZZLE_COUNT = 100
const TOLERANCE = 75
const TRUE_RATINGS = [900, 1400, 1600, 2000] as const
// Fixed per-run base seed keeps the whole report reproducible; each scenario gets
// its own derived seed so the four runs use independent coin-flip streams.
const BASE_SEED = 0x0c0d0705

const results: SimulationResult[] = TRUE_RATINGS.map((trueRating, index) =>
  simulate(trueRating, INITIAL_RATING, PUZZLE_COUNT, createRng(BASE_SEED + index)),
)

function buildReport(): string {
  const lines: string[] = []
  lines.push('# Rating Engine — Convergence Report')
  lines.push('')
  lines.push(
    'This report is generated by `src/engine/convergence.test.ts`. It simulates a ' +
      'user of a fixed *true* skill answering 100 puzzles. Each served puzzle is rated ' +
      'at the user’s current tracked rating (the pool-matching assumption), the user ' +
      'answers correctly with probability `expectedScore(trueRating, puzzleRating)`, and ' +
      'the tracked rating updates after every attempt via `updateRating` using the real ' +
      'K-schedule (32 for the first 20 rated attempts, then 24) and the 400 floor. Coin ' +
      'flips come from a seeded mulberry32 PRNG, so the numbers below are fully ' +
      'deterministic.',
  )
  lines.push('')
  lines.push(
    `Every tracked rating starts at ${String(INITIAL_RATING)} (the real new-user value). ` +
      `A scenario passes if the final tracked rating lands within ±${String(TOLERANCE)} ` +
      'of the true rating.',
  )
  lines.push('')
  lines.push('Regenerate with:')
  lines.push('')
  lines.push('```')
  lines.push('pnpm vitest run src/engine/convergence.test.ts')
  lines.push('```')
  lines.push('')

  const sampledAttempts: number[] = []
  for (let attempt = 0; attempt <= PUZZLE_COUNT; attempt += 10) {
    sampledAttempts.push(attempt)
  }

  for (const result of results) {
    const pass = Math.abs(result.delta) <= TOLERANCE
    lines.push(`## True rating ${String(result.trueRating)}`)
    lines.push('')
    lines.push('| Attempt | Tracked rating |')
    lines.push('| ---: | ---: |')
    for (const attempt of sampledAttempts) {
      const value = result.trajectory[attempt]
      const shown = value === undefined ? 'n/a' : String(roundForDisplay(value))
      lines.push(`| ${String(attempt)} | ${shown} |`)
    }
    lines.push('')
    lines.push(`- Final tracked rating: **${String(roundForDisplay(result.finalRating))}**`)
    lines.push(
      `- Delta from true rating: **${result.delta >= 0 ? '+' : ''}${String(roundForDisplay(result.delta))}**`,
    )
    lines.push(`- Result: **${pass ? 'PASS' : 'FAIL'}** (within ±${String(TOLERANCE)} band)`)
    lines.push('')
  }

  return lines.join('\n') + '\n'
}

describe('convergence simulation', () => {
  it('writes the human-readable convergence report', async () => {
    // Runs the raw report through Prettier before writing, matching what
    // lint-staged applies on commit — otherwise every `pnpm test` rewrites
    // this tracked file (different table-column padding) and leaves the
    // working tree dirty even though the underlying data is unchanged.
    const reportPath = resolve(process.cwd(), 'src/engine/CONVERGENCE.md')
    const config = await prettier.resolveConfig(reportPath)
    const formatted = await prettier.format(buildReport(), { ...config, filepath: reportPath })
    writeFileSync(reportPath, formatted)
    expect(results).toHaveLength(TRUE_RATINGS.length)
  })

  it('converges the true-1600 user to 1600 ± 75', () => {
    const result = results.find((r) => r.trueRating === 1600)
    expect(result).toBeDefined()
    expect(Math.abs(result?.delta ?? Infinity)).toBeLessThanOrEqual(TOLERANCE)
  })

  // The rating process is unbiased for every true rating: at equilibrium the served
  // puzzle equals the tracked rating, so the scored `expected` is 0.5 while the true
  // win probability is expectedScore(true, tracked); these balance only when
  // tracked === true. So the same ±75 band is justified across all four scenarios,
  // including the extremes — no widening needed.
  it.each(TRUE_RATINGS)('converges the true-%i user within ±75', (trueRating) => {
    const result = results.find((r) => r.trueRating === trueRating)
    expect(result).toBeDefined()
    expect(Math.abs(result?.delta ?? Infinity)).toBeLessThanOrEqual(TOLERANCE)
  })
})
