import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

// T4a: `POST /api/report` must validate `puzzleId` against the real content
// index (plan: "import the puzzleMeta module #82 created, do not duplicate
// it"). F7 finding: that module (src/content/index.ts's `puzzleMeta`) is
// populated via `import { PUZZLE_META } from 'virtual:codoro-puzzle-meta'`
// -- a Vite virtual module resolved by vite.config.ts's puzzleMetaPlugin,
// which only exists inside the root Vite build. workers/ is a separate
// package, bundled by wrangler's esbuild, which has no knowledge of Vite
// plugins -- a literal `import ... from '../src/content'` would fail to
// resolve that virtual specifier the moment wrangler tried to bundle it.
//
// So this script is the closest honest equivalent, not a duplicate of the
// module: it reads the exact same source files puzzleMetaPlugin reads
// (src/content/puzzles/**/*.json, walked the same way, sorted the same
// way -- see that plugin's own readPuzzleMeta() in vite.config.ts), and
// writes a plain generated .ts file workers/src code can statically
// import. There is exactly one source of truth (the puzzle JSON files);
// this and puzzleMetaPlugin are two independent readers of it, not two
// copies of derived data maintained by hand.
//
// Run before typecheck/lint/test/deploy (see package.json) so the
// generated file is never stale relative to content -- same freshness
// guarantee T2's readD1Migrations() gives migrations, just via a plain
// script instead of a vitest-pool-workers hook, since this output needs
// to exist for `tsc`/`eslint` too, not only tests.

const here = dirname(fileURLToPath(import.meta.url))
const puzzlesDir = join(here, '..', '..', 'src', 'content', 'puzzles')
const outFile = join(here, '..', 'src', 'puzzleIds.generated.ts')

function walk(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const fullPath = join(dir, entry.name)
    if (entry.isDirectory()) return walk(fullPath)
    return entry.name.endsWith('.json') ? [fullPath] : []
  })
}

const ids = walk(puzzlesDir)
  .sort()
  .map((filePath) => JSON.parse(readFileSync(filePath, 'utf-8')).id)

const contents = `// GENERATED by workers/scripts/generatePuzzleIds.mjs -- do not edit by
// hand, and do not commit (gitignored). Regenerated automatically before
// typecheck/lint/test/deploy (workers/package.json). Source of truth:
// src/content/puzzles/**/*.json -- the same files vite.config.ts's
// puzzleMetaPlugin reads for the SPA's puzzleMeta export; see that
// plugin's comment, and this script's own comment, for why this Worker
// package reads them independently instead of importing that module.
export const VALID_PUZZLE_IDS: ReadonlySet<string> = new Set(${JSON.stringify(ids)})
`

writeFileSync(outFile, contents)
console.log(`generatePuzzleIds: wrote ${String(ids.length)} ids to ${outFile}`)
